### ISSUE TITLE
How to use amazon-book dataset

### ISSUE THREAD

**Issue by wosigewozai-ffmm** [ZJU-DAILY/MetaKG#1]
when I was running the construct_data.py, it Error Display “[Errno 2] No such file or directory: './datasets/amazon-book/user_list.txt'”，
where can I get the file "user_list.txt"？

**Comment by kuiniela** [comment]
Hey JiaRan,I have the same question.Did you solve it?

**Comment by yuntaod** [comment]
it can be found here: https://github.com/xiangwang1223/knowledge_graph_attention_network/tree/master/Data/amazon-book

**Comment by kuiniela** [comment]
> 可以在这里找到： https: [//github.com/xiangwang1223/knowledge_graph_attention_network/tree/master/Data/amazon-book](https://github.com/xiangwang1223/knowledge_graph_attention_network/tree/master/Data/amazon-book)

大佬好，construct_data.py文件的merge_train_vali_test这个函数有一行lines_vali = open(path+'valid1.txt', 'r').readlines()，这个valid1.txt文件在那儿并没有呀
