### ISSUE TITLE
NameError: name 'test_user_set' is not defined

### ISSUE THREAD

**Issue by kuiniela** [ZJU-DAILY/MetaKG#3]
It remind me about this when I run python main.py --dataset last-fm --use_meta_model True
Is there anyone can help?

Environment Requirements
Windows 11
Python = 3.8&3.10
PyTorch 1.12.1
A Nvidia GPU with cuda 11.8

**Comment by kuiniela** [comment]
@zealscott @xj-zhu98

**Comment by adroitwolf** [comment]
hello,this problem is aslo happening on my pc,could you tell me how to finish this problem? plz
